version: '3.8'

services:
  # Service PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: drupal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-drupal}
      POSTGRES_USER: ${POSTGRES_USER:-drupal}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-drupal}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - drupal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-drupal}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service Elasticsearch
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: drupal-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=drupal-cluster
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - drupal-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  # Service Drupal
  drupal:
    image: drupal:10-apache
    container_name: drupal-app
    restart: unless-stopped
    ports:
      - "${DRUPAL_PORT:-8080}:80"
    environment:
      # Configuration de la base de données
      POSTGRES_DB: ${POSTGRES_DB:-drupal}
      POSTGRES_USER: ${POSTGRES_USER:-drupal}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-drupal}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      # Configuration Elasticsearch
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
    volumes:
      # Templates de modules et thèmes (versionnés)
      - ./templates/drupal/modules/drupalmania_module:/opt/drupal/web/modules/custom/drupalmania_module
      - ./templates/drupal/themes/drupalmania_theme:/opt/drupal/web/themes/custom/drupalmania_theme
      # Données persistantes (non versionnées)
      - ./data/drupal/modules:/opt/drupal/web/modules/custom/user_modules
      - ./data/drupal/themes:/opt/drupal/web/themes/custom/user_themes
      - ./data/drupal/sites:/opt/drupal/web/sites
      - ./data/drupal/profiles:/opt/drupal/web/profiles
    networks:
      - drupal-network
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

networks:
  drupal-network:
    driver: bridge

volumes:
  postgres-data:
  drupal-data:
