version: '3.8'

services:
  # Service PostgreSQL
  postgres:
    image: postgres:17-alpine
    container_name: drupal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-drupal}
      POSTGRES_USER: ${POSTGRES_USER:-drupal}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-drupal}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - drupal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-drupal}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service Elasticsearch
  # Updated to 8.19.5 to fix security vulnerabilities:
  # - CVE-2025-37727 (CVSS 5.3): Information disclosure in audit logging
  # - CVE-2025-37728 (CVSS 5.4): CrowdStrike connector vulnerability
  # Using official Elastic registry: docker.elastic.co
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.5
    container_name: drupal-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=drupal-cluster
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - drupal-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=5s || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  # Service Fluentd (mode asynchrone)
  fluentd:
    image: fluent/fluentd:v1.19-debian-2
    container_name: drupal-fluentd
    restart: unless-stopped
    user: root
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./config/fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./data/fluentd/log:/fluentd/log
    networks:
      - drupal-network
    depends_on:
      elasticsearch:
        condition: service_healthy
    command: >
      sh -c "gem install fluent-plugin-elasticsearch --no-document &&
             fluentd -c /fluentd/etc/fluent.conf"

  # Service Kibana
  # Updated to 8.19.5 to fix security vulnerabilities:
  # - CVE-2025-25009 (CVSS 8.7): XSS in case file upload functionality
  # - CVE-2025-25018 (CVSS 8.7): Stored XSS in Fleet/Integrations interface
  # - CVE-2025-25017 (CVSS 8.2): Vulnerability in Vega visualization engine
  # Using official Elastic registry: docker.elastic.co
  kibana:
    image: docker.elastic.co/kibana/kibana:8.19.5
    container_name: drupal-kibana
    restart: unless-stopped
    ports:
      - "${KIBANA_PORT:-5601}:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SERVER_NAME=drupal-kibana
      - SERVER_HOST=0.0.0.0
    networks:
      - drupal-network
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Service Drupal
  # Updated to 11.2-apache to fix security vulnerabilities:
  # - CVE-2024-55636 (CVSS 9.8): PHP Object Injection vulnerability (affects 11.0.0 - 11.0.7)
  # Using drupal:11.2-apache (currently 11.2.5, released October 2025)
  drupal:
    image: drupal:11.2-apache
    container_name: drupal-app
    restart: unless-stopped
    ports:
      - "${DRUPAL_PORT:-8080}:80"
    environment:
      # Configuration de la base de données
      POSTGRES_DB: ${POSTGRES_DB:-drupal}
      POSTGRES_USER: ${POSTGRES_USER:-drupal}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-drupal}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      # Configuration Elasticsearch
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
    volumes:
      # Templates de modules et thèmes (versionnés)
      - ./templates/drupal/modules/drupalmania_module:/opt/drupal/web/modules/custom/drupalmania_module
      - ./templates/drupal/themes/drupalmania_theme:/opt/drupal/web/themes/custom/drupalmania_theme
      # Données persistantes (non versionnées)
      - ./data/drupal/modules:/opt/drupal/web/modules/custom/user_modules
      - ./data/drupal/themes:/opt/drupal/web/themes/custom/user_themes
      - ./data/drupal/sites:/opt/drupal/web/sites
      - ./data/drupal/profiles:/opt/drupal/web/profiles
    networks:
      - drupal-network
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"
        fluentd-retry-wait: "1s"
        fluentd-max-retries: "30"
        tag: docker.drupal
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      fluentd:
        condition: service_started

networks:
  drupal-network:
    driver: bridge

volumes:
  postgres-data:
  drupal-data:
